package com.example.blog.domain.account;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.USER_TYPE
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.IS_PROD_TEST
     *
     * @mbg.generated
     */
    private Byte isProdTest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.IS_DELETE
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.USE_ROLE_FUN
     *
     * @mbg.generated
     */
    private Byte useRoleFun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.USE_ROLE_DATA
     *
     * @mbg.generated
     */
    private Byte useRoleData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.USE_ROLE_POSITION
     *
     * @mbg.generated
     */
    private Byte useRolePosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.OP_USER
     *
     * @mbg.generated
     */
    private String opUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_user.OP_TIME
     *
     * @mbg.generated
     */
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table au_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.USER_ID
     *
     * @return the value of au_user.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.USER_ID
     *
     * @param userId the value for au_user.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.USER_TYPE
     *
     * @return the value of au_user.USER_TYPE
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.USER_TYPE
     *
     * @param userType the value for au_user.USER_TYPE
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.IS_PROD_TEST
     *
     * @return the value of au_user.IS_PROD_TEST
     *
     * @mbg.generated
     */
    public Byte getIsProdTest() {
        return isProdTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.IS_PROD_TEST
     *
     * @param isProdTest the value for au_user.IS_PROD_TEST
     *
     * @mbg.generated
     */
    public void setIsProdTest(Byte isProdTest) {
        this.isProdTest = isProdTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.IS_DELETE
     *
     * @return the value of au_user.IS_DELETE
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.IS_DELETE
     *
     * @param isDelete the value for au_user.IS_DELETE
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.USE_ROLE_FUN
     *
     * @return the value of au_user.USE_ROLE_FUN
     *
     * @mbg.generated
     */
    public Byte getUseRoleFun() {
        return useRoleFun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.USE_ROLE_FUN
     *
     * @param useRoleFun the value for au_user.USE_ROLE_FUN
     *
     * @mbg.generated
     */
    public void setUseRoleFun(Byte useRoleFun) {
        this.useRoleFun = useRoleFun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.USE_ROLE_DATA
     *
     * @return the value of au_user.USE_ROLE_DATA
     *
     * @mbg.generated
     */
    public Byte getUseRoleData() {
        return useRoleData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.USE_ROLE_DATA
     *
     * @param useRoleData the value for au_user.USE_ROLE_DATA
     *
     * @mbg.generated
     */
    public void setUseRoleData(Byte useRoleData) {
        this.useRoleData = useRoleData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.USE_ROLE_POSITION
     *
     * @return the value of au_user.USE_ROLE_POSITION
     *
     * @mbg.generated
     */
    public Byte getUseRolePosition() {
        return useRolePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.USE_ROLE_POSITION
     *
     * @param useRolePosition the value for au_user.USE_ROLE_POSITION
     *
     * @mbg.generated
     */
    public void setUseRolePosition(Byte useRolePosition) {
        this.useRolePosition = useRolePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.CREATE_USER
     *
     * @return the value of au_user.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.CREATE_USER
     *
     * @param createUser the value for au_user.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.CREATE_TIME
     *
     * @return the value of au_user.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.CREATE_TIME
     *
     * @param createTime the value for au_user.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.OP_USER
     *
     * @return the value of au_user.OP_USER
     *
     * @mbg.generated
     */
    public String getOpUser() {
        return opUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.OP_USER
     *
     * @param opUser the value for au_user.OP_USER
     *
     * @mbg.generated
     */
    public void setOpUser(String opUser) {
        this.opUser = opUser == null ? null : opUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_user.OP_TIME
     *
     * @return the value of au_user.OP_TIME
     *
     * @mbg.generated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_user.OP_TIME
     *
     * @param opTime the value for au_user.OP_TIME
     *
     * @mbg.generated
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }
}